### ISSUE TITLE
how much VRAM does this need

### ISSUE THREAD

**Issue by Stable777** [yandex-research/switti#5]
can this work on a phone?

**Comment by RealAntonVoronov** [comment]
Switti requires 6.88 GB VRAM to be loaded in torch.bfloat16. Then, an inference with a batch_size=1 with guidance turned on and disabled at the last two scales requires additional 0.54 GB, resulting in around 7.44 GB in total, with full guidance -> 7.94 GB. All in all, 8 GB GPU should be sufficient for inference in bf16.

As for running on mobile devices, I think it is possible to run Switti with the help of further quantization or weights offloading. However, adaptation to mobile devices is not in our current scope of work. But we welcome any contributions
