### ISSUE TITLE
Inference code mistake.

### ISSUE THREAD

**Issue by Klayand** [yandex-research/switti#6]
![图片](https://github.com/user-attachments/assets/e5b6dd13-2526-4a5a-a7c3-e62adad3d108)

`dtype=torch.bfloat16` should be `torch_dtype=torch.bfloat16`

**Comment by Klayand** [comment]
Sorry to disturb you, besides:
`pipe = SwittiPipeline.from_pretrained(model_path, dtype=torch.bfloat16).to(device)
`
should be `pipe = SwittiPipeline.from_pretrained(model_path, device=device, torch_dtype=torch.bfloat16)`

**Comment by Godofnothing** [comment]
@Klayand thanks for pointing this out!
I'll fix it.
